steps:
  - name: 'node'
    id: 'Install node'
    dir: './nodeApi/src'
    args: ["npm", "install"]

  - name: 'node'
    id: 'Build node'
    dir: './nodeApi/src'
    args: ["npm", build"]

  - name: 'node'
    id: 'Test node'
    dir: './nodeApi/src'
    args: ["npm", "test"]

# steps:
# - name: 'gcr.io/cloud-builders/npm' 
# args: ['install']

# - name: 'gcr.io/cloud-builders/npm' 
# args: ['test']

# - name: "gcr.io/cloud-builders/gcloud"
# args: ["app", "deploy"]

# timeout: "1600s"
