steps:
  # - name: 'maven'
  #   id: maven-build
  #   args: ["mvn", "clean", "install", "-DskipTest"]

  - name: 'node'
    args: ["npm", "install"]

  - name: 'node'
    args: ["npm", "run", "build"]

  - name: 'node'
    args: ["npm", "run", "test"]

# steps:
# - name: 'gcr.io/cloud-builders/npm' 
# args: ['install']

# - name: 'gcr.io/cloud-builders/npm' 
# args: ['test']

# - name: "gcr.io/cloud-builders/gcloud"
# args: ["app", "deploy"]

# timeout: "1600s"
