steps:
  # - name: 'maven'
  #   id: maven-build
  #   args: ["mvn", "clean", "install", "-DskipTest"]



# Go to node Directory
  - name: 'node'
    id: 'Install node'
    dir: './nodeApi/src'
    args: ["npm ", "install"]

  - name: 'node'
    id: 'Build node'
    dir: './nodeApi/src'
    args: ["npm", "run", "build"]

  - name: 'node'
    id: 'Test node'
    dir: './nodeApi/src'
    args: ["npm", "run", "test"]

# steps:
# - name: 'gcr.io/cloud-builders/npm' 
# args: ['install']

# - name: 'gcr.io/cloud-builders/npm' 
# args: ['test']

# - name: "gcr.io/cloud-builders/gcloud"
# args: ["app", "deploy"]

# timeout: "1600s"
