steps:
  # - name: 'maven'
  #   id: maven-build
  #   args: ["mvn", "clean", "install", "-DskipTest"]



# Go to node Directory
  - name: 'node'
    id: 'Install node'
    entrypoint: '/bin/bash'
    args: ["cd ", "nodeApi/src"]

  - name: 'node'
    id: 'Build node'
    args: ["npm", "run", "build"]

  - name: 'node'
    id: 'Test node'
    args: ["npm", "run", "test"]

# steps:
# - name: 'gcr.io/cloud-builders/npm' 
# args: ['install']

# - name: 'gcr.io/cloud-builders/npm' 
# args: ['test']

# - name: "gcr.io/cloud-builders/gcloud"
# args: ["app", "deploy"]

# timeout: "1600s"
